<a href="https://colab.research.google.com/github/sanjana2343/git333/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data={'name':['Rupa','sita','Getha'],
'Age':[25,30,35],
'city':['Bagalkot','solapur','Gulbarga']}
df=pd.DataFrame(data)
print(df)

    name  Age      city
0   Rupa   25  Bagalkot
1   sita   30   solapur
2  Getha   35  Gulbarga


In [ ]:
import pandas as pd
data={'name':['Rupa','sita','Getha'],
'Age':[25,30,35],
'city':['Bagalkot','solapur','Gulbarga']}
df=sorted=df.sort_values(by='Age',ascending=False')
print(df_sorted)

SyntaxError: unterminated string literal (detected at line 5) (ipython-input-8-875944672.py, line 5)

In [ ]:
import pandas as pd
data={'name':['Rupa','sita','Getha'],
      'Age':[25,30,35],
      'city':['Bagalkot','solapur','Gulbarga']}
df=pd.DataFrame(data)
salary=[50000,60000,70000]
df['salary']=salary
print("new dataFrame after inserting new column'Salary'")
print(df)

new dataFrame after inserting new column'Salary'
    name  Age      city  salary
0   Rupa   25  Bagalkot   50000
1   sita   30   solapur   60000
2  Getha   35  Gulbarga   70000


In [ ]:
import pandas as pd
data={'name':['Rupa','sita','Getha'],
      'age':[25,30,35],
      'city':['Bagalkot','solapur','Gulbarga']}
df=pd.DataFrame(data)
age_above_30=df[df['age']>30]
print(age_above_30)


    name  age      city
2  Getha   35  Gulbarga


In [ ]:
import pandas as pd
data={'name':['Rupa','sita','Getha'],
      'age':[25,30,35],
      'city':['Bagalkot','solapur','Gulbarga']}
df=pd.DataFrame(data)
df['city']=df['city'].replace('solapur','bagalkot')
print(df)

    name  age      city
0   Rupa   25  Bagalkot
1   sita   30  bagalkot
2  Getha   35  Gulbarga


In [ ]:
import pandas as pd
data={'name':['Rupa','sita','Getha'],
      'age':[25,30,35],
      'city':['Bagalkot','solapur','Gulbarga']}
df=pd.DataFrame(data)
df=df.drop('city',axis=1)
print(df)

    name  age
0   Rupa   25
1   sita   30
2  Getha   35


In [ ]:
import pandas as pd
data={'name':['Rupa','sita','Getha'],
      'age':[25,30,35],
      'city':['Bagalkot','solapur','Gulbarga']}
df=pd.DataFrame(data)
average=df['age'].mean()
print('average',average)

average 30.0


In [ ]:
import pandas as pd
data={'name':['rupa','sita','getha'],
      'age':[25,30,35],
      'city':['bagalkot','solapur','gulbarga']}
df=pd.DataFrame(data)
is_from_bagalkot=(df['city']=='bagalkot').any()
print("is anyone from bagalkot ?",is_from_bagalkot)

is anyone from bagalkot ? True


In [ ]:
import pandas as pd
data={'name':['rupa','sita','getha'],
      'age':[25,30,35],
      'city':['bagalkot','solapur','gulbarga']}
df=pd.DataFrame(data)
info1=df[df['name']=='sita']
print(info1)

   name  age     city
1  sita   30  solapur


In [ ]:
import pandas as pd
data={'name':['rupa','sita','getha'],
      'age':[25,30,35],
      'city':['bagalkot','solapur','gulbarga']}
df=pd.DataFrame(data)
count_c=df['city'].value_counts()
print(count_c)


city
bagalkot    1
solapur     1
gulbarga    1
Name: count, dtype: int64


In [ ]:
import pandas as pd
data={'name':['rupa','sita','getha'],
      'age':[25,30,35],
      'city':['bagalkot','solapur','gulbarga'],
      'salary':[50000,60000,70000]}
df=pd.DataFrame(data)
max_s=df[df['salary']==df['salary'].max()]
print(max_s)

    name  age      city  salary
2  getha   35  gulbarga   70000


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.sum())
print(arr.mean())
print(arr.max())




10
2.5
4


In [ ]:
import numpy as np
import random
array=np.random.randint(16,size=(4,4))
print("input array:\n",array)
print("largest number in y axis:",np.max(array,axis=1))
print("largest number in y axis:",np.max(array,axis=0))

input array:
 [[ 8  8  7 11]
 [15  0  7  6]
 [ 7  4  3  4]
 [ 6  5 13 14]]
largest number in y axis: [11 15  7 14]
largest number in y axis: [15  8 13 14]


In [ ]:
import numpy as np
import random
array=np.random.randint(5,size=(4,4))
print("input array:\n",array)
print("Smallest  number in x axis:",np.min(array,axis=1))
print("Smallest number in y axis:",np.min(array,axis=0))

input array:
 [[4 0 2 0]
 [3 3 1 0]
 [3 0 2 1]
 [1 3 4 1]]
Smallest  number in x axis: [0 0 0 1]
Smaillest number in y axis: [1 0 1 0]


In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr+2)
print(np.sin(arr))


[3 4 5]
[0.84147098 0.90929743 0.14112001]


In [ ]:
import numpy as np
arr=np.array([1,2,3])
arr2=np.array([1,2,3])
print(arr+arr2)


[2 4 6]


In [ ]:

Squared=list(map(lambda x:x**2,arr))
print("Squared using map:",Squared)

Squared using map: [np.int64(1), np.int64(4), np.int64(9)]


In [ ]:
def Square(number):
  return number*number
nums=[1,2,3,4,5]
Squared_numbers=list(map(Square,nums))
print(Squared_numbers)

[1, 4, 9, 16, 25]


In [ ]:
def Square(number):
  return number*number
num1=[1,2,3,4,5,6]
Squareofnum1=list(map(lambda n:n*n,num1))
print(Squareofnum1)

[1, 4, 9, 16, 25, 36]


In [ ]:
def is_even(n):
  if n%2==0:
    return True
  else:
      return False
nums=[1,2,3,4]
evens=list(filter(is_even,nums))
print(evens)

[2, 4]


In [ ]:
arr=[1,2,3,4]
even=list(filter(lambda x:x%2==0,arr))
print("Even numbers:",even)

Even numbers: [2, 4]


In [ ]:
from functools import reduce
def sum_all(a,b):
  return a+b
nums=[1,2,3,4]
sum=reduce(sum_all,nums)
print(sum)

10


In [ ]:
from functools import reduce
nums=[1,2,3,4]
total=reduce(lambda x,y:x+y,nums)
print("Sum using reduce:",total)

Sum using reduce: 10


In [ ]:
from functools import reduce
nums=[1,2,3,4]
evens=list(filter(lambda n:n%2==0,nums))
print(evens)

[2, 4]


In [ ]:
import pandas as pd
data=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(data)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
import pandas as pd
data={
    'Name':['Alice','bob','charile'],
    'Age':[25,30,35],
    'city':['Delhi','Mumbai','bangalore']
}
df=pd.DataFrame(data)
print(df)

      Name  Age       city
0    Alice   25      Delhi
1      bob   30     Mumbai
2  charile   35  bangalore


In [ ]:
import pandas as pd
list=['Apple','Banana','pine apple','grapes','watermelon']
df=pd.DataFrame(list)
print(df)

            0
0       Apple
1      Banana
2  pine apple
3      grapes
4  watermelon


In [ ]:
df=pd.read_csv('/content/student.csv')
df.to_csv('output.csv',index=False)
print(df)
print(df.head())

      name   reg.no   sub1     sub2
0    sanvi  23cs001  maths  science
1  sukruta  23cs002  maths  science
2   bhoomi  23cs003  maths  science
      name   reg.no   sub1     sub2
0    sanvi  23cs001  maths  science
1  sukruta  23cs002  maths  science
2   bhoomi  23cs003  maths  science


In [ ]:
df=pd.read_csv('/content/student1.csv')
df.to_csv('output.csv',index=False)
print(df)
print(df.head())
print(df.tail())

   sl.no    regno     name   sub1     sub2
0      1  23cs001  sukruta  maths  biology
1      2  23cs002   bhoomi  maths  biology
2      3  23cs003    sanvi  maths  biology
   sl.no    regno     name   sub1     sub2
0      1  23cs001  sukruta  maths  biology
1      2  23cs002   bhoomi  maths  biology
2      3  23cs003    sanvi  maths  biology
   sl.no    regno     name   sub1     sub2
0      1  23cs001  sukruta  maths  biology
1      2  23cs002   bhoomi  maths  biology
2      3  23cs003    sanvi  maths  biology


In [ ]:
import pandas as pd
data={
    'Name':['Alice','bob','charile'],
    'Age':[25,30,35],
    'city':['Delhi','Mumbai','bangalore']
}
df=pd.DataFrame(data)
print(df['Name'])
print(df.loc[0])
print(df.iloc[1])


0      Alice
1        bob
2    charile
Name: Name, dtype: object
Name    Alice
Age        25
city    Delhi
Name: 0, dtype: object
Name       bob
Age         30
city    Mumbai
Name: 1, dtype: object


In [ ]:
import pandas as pd
data={
    'Name':['Alice','bob','charile'],
    'Age':[25,30,35],
    'city':['Delhi','Mumbai','bangalore']
}
df=pd.DataFrame(data)
filtered=df[df['Age']>25]
print(filtered)

      Name  Age       city
1      bob   30     Mumbai
2  charile   35  bangalore


In [ ]:
import pandas as pd
data={
    'Name':['Alice','bob','charile'],
    'Age':[25,30,35],
    'city':['Delhi','Mumbai','bangalore']
}
df=pd.DataFrame(data)
df['salary']=[50000,60000,70000]
df['Age']=df['Age']+1
print(df)

      Name  Age       city  salary
0    Alice   26      Delhi   50000
1      bob   31     Mumbai   60000
2  charile   36  bangalore   70000


In [ ]:
import pandas as pd
data={'name':['TOM','nick','krish','jack'],
'Age':[20,21,19,18]}
df=pd.DataFrame(data)
print(df)

    name  Age
0    TOM   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
import pandas as pd
data={'Department':['HR','IT','FInance','HR','Finance','IT'],
'Employee':['Alice','charlie','David','Eva','Frame','Frame'],
'salary':[50000,30000,65000,70000,720000,55000],
'Age':[25,30,28,32,40,38]}
df=pd.DataFrame(data)
print(df)


  Department Employee  salary  Age
0         HR    Alice   50000   25
1         IT  charlie   30000   30
2    FInance    David   65000   28
3         HR      Eva   70000   32
4    Finance    Frame  720000   40
5         IT    Frame   55000   38


In [ ]:
import pandas as pd
data={'Department':['HR','IT','FInance','HR','Finance','IT'],
'Employee':['Alice','charlie','David','Eva','Frame','Frame'],
'salary':[50000,30000,65000,70000,720000,55000],
'Age':[25,30,28,32,40,38]}
df=pd.DataFrame(data)
print(df['salary'].mean())
print(df['Age'].max())


165000.0
40


In [ ]:
import pandas as pd
data={'Department':['HR','IT','FInance','HR','Finance','IT'],
'Employee':['Alice','charlie','David','Eva','Frame','Frame'],
'salary':[50000,30000,65000,70000,720000,55000],
'Age':[25,30,28,32,40,38]}
df=pd.DataFrame(data)
grouped=df.groupby('Department')['salary'].mean()
print(grouped)


Department
FInance     65000.0
Finance    720000.0
HR          60000.0
IT          42500.0
Name: salary, dtype: float64


In [ ]:
import pandas as pd
data={'Department':['HR','IT','FInance','HR','Finance','IT'],
'Employee':['Alice','charlie','David','Eva','Frame','Frame'],
'salary':[50000,30000,65000,70000,720000,55000],
'Age':[25,30,28,32,40,38]}
df=pd.DataFrame(data)
grouped=df.groupby('Department')['salary'].agg(['mean','max','min'])
print(grouped)


                mean     max     min
Department                          
FInance      65000.0   65000   65000
Finance     720000.0  720000  720000
HR           60000.0   70000   50000
IT           42500.0   55000   30000


In [ ]:
import pandas as pd
data={'Department':['HR','IT','FInance','HR','Finance','IT'],
'Employee':['Alice','charlie','David','Eva','Frame','Frame'],
'salary':[50000,30000,65000,70000,720000,55000],
'Age':[25,30,28,32,40,38]}
df=pd.DataFrame(data)
df['location']=['Mumbai','Delhi','Mumbai','Delhi','delhi','mumbai']
grouped=df.groupby(['Department','location'])['salary'].mean()
print(grouped)


Department  location
FInance     Mumbai       65000.0
Finance     delhi       720000.0
HR          Delhi        70000.0
            Mumbai       50000.0
IT          Delhi        30000.0
            mumbai       55000.0
Name: salary, dtype: float64


In [ ]:
import pandas as pd
data={'Department':['HR','IT','FInance','HR','Finance','IT'],
'Employee':['Alice','charlie','David','Eva','Frame','Frame'],
'salary':[50000,30000,65000,70000,720000,55000],
'Age':[25,30,28,32,40,38]}
df=pd.DataFrame(data)
df['location']=['Mumbai','Delhi','Mumbai','Delhi','delhi','mumbai']
grouped=df.groupby(['Department','location'])['salary'].mean()
print(grouped)


Department  location
FInance     Mumbai       65000.0
Finance     delhi       720000.0
HR          Delhi        70000.0
            Mumbai       50000.0
IT          Delhi        30000.0
            mumbai       55000.0
Name: salary, dtype: float64


In [ ]:
import pandas as pd
data={'Department':['HR','IT','FInance','HR','Finance','IT'],
'Employee':['Alice','charlie','David','Eva','Frame','Frame'],
'salary':[50000,30000,65000,70000,720000,55000],
'Age':[25,30,28,32,40,38]}
df=pd.DataFrame(data)
result=df.groupby('Department').agg({'salary':'mean','Age':['min','max']})
print(result)


              salary Age    
                mean min max
Department                  
FInance      65000.0  28  28
Finance     720000.0  40  40
HR           60000.0  25  32
IT           42500.0  30  38


In [ ]:
import pandas as pd
d1={"Name":["pandas","lisa","David"],
    "ID":[1,2,3],"Role":["CEO","Editor","Audio"]}
df=pd.DataFrame(d1)
print(df)
df_melted=pd.melt(df,id_vars=["ID"],
value_vars=["Name","Role"])
print(df_melted)

     Name  ID    Role
0  pandas   1     CEO
1    lisa   2  Editor
2   David   3   Audio
   ID variable   value
0   1     Name  pandas
1   2     Name    lisa
2   3     Name   David
3   1     Role     CEO
4   2     Role  Editor
5   3     Role   Audio


In [ ]:
import pandas as pd
data={'Date':['2024-01-01','2024-01-01','2024-01-02','2024-01-02'],
      'city':['Mumbai','Delhi','Mumbai','Delhi'],
      'Temperature':[33,28,34,27]}
df=pd.DataFrame(data)
print("Original:\n",df)
pivoted=df.pivot(index='Date',columns='city',values='Temperature')
print("\n",pivoted)

Original:
          Date    city  Temperature
0  2024-01-01  Mumbai           33
1  2024-01-01   Delhi           28
2  2024-01-02  Mumbai           34
3  2024-01-02   Delhi           27

 city        Delhi  Mumbai
Date                     
2024-01-01     28      33
2024-01-02     27      34


In [ ]:
import pandas as pd
data={'student':['Alice','Bob','charlie'],
      'maths':[85,90,78],
      'English':[75,80,72]}
df=pd.DataFrame(data)
print("Original wide DataFrame:\n",df)

Original wide DataFrame:
    student  maths  English
0    Alice     85       75
1      Bob     90       80
2  charlie     78       72


In [ ]:
import pandas as pd
melted_df=pd.melt(df,id_vars=['student'],var_name='subject',value_name='marks')
print("\n melted Long DataFrame:\n",melted_df)


 melted Long DataFrame:
    student  subject  marks
0    Alice    maths     85
1      Bob    maths     90
2  charlie    maths     78
3    Alice  English     75
4      Bob  English     80
5  charlie  English     72


In [ ]:
import pandas as pdt
import numpy as np
dates=pd.date_range(start='2024-01-01',periods=10,freq='D')
ts=pd.Series(np.random.rand(len(dates)))
print(ts)

0    0.355245
1    0.839056
2    0.841276
3    0.739894
4    0.307002
5    0.932618
6    0.525767
7    0.768439
8    0.895341
9    0.488287
dtype: float64


In [ ]:
df=pd.DataFrame({'Date':['2024-01-01','2024-01-02','2024-01-03'],
                 'value':[120,135,150]})
df['Date']=pd.to_datetime(df['Date'])
print(df)

        Date  value
0 2024-01-01    120
1 2024-01-02    135
2 2024-01-03    150


In [ ]:
import pandas as pd
import numpy as np
# Generate date range (10 daily periods starting from Jan 1, 2024)
dates = pd.date_range(start='2024-01-01', periods=10, freq='D')
# Create a time series
ts = pd.Series(np.random.randint(100, 200, size=10), index=dates)
print(ts['2024-01-04'])
print(ts['2024-01-03':'2024-01-07'])
print(ts['2024-01'])

177
2024-01-03    105
2024-01-04    177
2024-01-05    138
2024-01-06    195
2024-01-07    190
Freq: D, dtype: int64
2024-01-01    192
2024-01-02    161
2024-01-03    105
2024-01-04    177
2024-01-05    138
2024-01-06    195
2024-01-07    190
2024-01-08    170
2024-01-09    194
2024-01-10    175
Freq: D, dtype: int64


In [ ]:
import pandas as pd
import numpy as np
from functools import reduce
df=pd.DataFrame({'Name':['Alice','Bob','charlie','Davide'],
                 'Age':[25,32,30,29],
                 'salary':[50000,60000,55000,52000]})
print(df)

      Name  Age  salary
0    Alice   25   50000
1      Bob   32   60000
2  charlie   30   55000
3   Davide   29   52000


In [ ]:
import pandas as pd
import numpy as np
from functools import reduce
df=pd.DataFrame({'Name':['Alice','Bob','charlie','Davide'],
                 'Age':[25,32,30,29],
                 'salary':[50000,60000,55000,52000]})
df['updated_salary']=df['salary'].apply(lambda x:x*1.10)
df['Age_group']=df['Age'].apply(lambda x:'Young' if x<30 else 'Adult')

print(df)


      Name  Age  salary  updated_salary Age_group
0    Alice   25   50000         55000.0     Young
1      Bob   32   60000         66000.0     Adult
2  charlie   30   55000         60500.0     Adult
3   Davide   29   52000         57200.0     Young


In [ ]:
import pandas as pd
import numpy as np
from functools import reduce
df=pd.DataFrame({'Name':['Alice','Bob','charlie','Davide'],
                 'Age':[25,32,30,29],
                 'salary':[50000,60000,55000,52000]})
df['Name_upper']=df['Name'].map(lambda x:x.upper())
Salary_levels={50000:'Low',60000:'Medium',60000:'High'}
df['Salary_levels']=df['salary'].map(Salary_levels)
print(df)

      Name  Age  salary Name_upper Salary_levels
0    Alice   25   50000      ALICE           Low
1      Bob   32   60000        BOB          High
2  charlie   30   55000    CHARLIE           NaN
3   Davide   29   52000     DAVIDE           NaN


In [ ]:
import pandas as pd
import numpy as np
from functools import reduce
df=pd.DataFrame({'Name':['Alice','Bob','charlie','Davide'],
                 'Age':[25,32,30,29],
                 'salary':[50000,60000,55000,52000]})
filtered_df=df[df['salary']>5200]
filtered_df=df[df['Name'].apply(lambda x:x.startswith('A'))]
print(filtered_df)

    Name  Age  salary
0  Alice   25   50000


In [ ]:
import pandas as pd
import numpy as np
from functools import reduce
df=pd.DataFrame({'Name':['Alice','Bob','charlie','Davide'],
                 'Age':[25,32,30,29],
                 'salary':[50000,60000,55000,52000]})
df['Name_Age']=df.apply(lambda row:reduce(lambda a,b:str(a)+'_'+str(b),[row['name'],row['age']]))
print(df)

KeyError: 'name'